package view;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class DndFrame extends javax.swing.JFrame {

    private JPanel campaignPanel;
    private JPanel characterPanel;
    private JPanel diceThrowPanel;
    private static Connection conn;
    
    /**
     * Creates new form DndFrame
     */
    public DndFrame() {
        initComponents();
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dnd", "root", "1234");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "A kapcsolodás az adatbázishoz nem sikerült, emiatt a program kilép.", "Adatbázis hiba!", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
        
        campaignPanel = new CampaignPanel();
        characterPanel = new CharacterPanel();
        diceThrowPanel = new DiceThrowPanel();
        this.add(campaignPanel);
        this.add(characterPanel);
        this.add(diceThrowPanel);
    }
    
    /**
     * Returns the database connection.
     * @return the database connection
     */
    public static Connection getConn() {
        return conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JMenuBar();
        menuView = new javax.swing.JMenu();
        menuViewCampaign = new javax.swing.JMenuItem();
        menuViewCharacter = new javax.swing.JMenuItem();
        menuViewDiceThrow = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dungeons & Dragons");
        setName(""); // NOI18N
        setResizable(false);

        menuView.setText("Nézetváltás");

        menuViewCampaign.setText("Kampány-kezelő");
        menuViewCampaign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewCampaignActionPerformed(evt);
            }
        });
        menuView.add(menuViewCampaign);

        menuViewCharacter.setText("Karakter-kezelő");
        menuViewCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewCharacterActionPerformed(evt);
            }
        });
        menuView.add(menuViewCharacter);

        menuViewDiceThrow.setText("Kockadobás");
        menuViewDiceThrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewDiceThrowActionPerformed(evt);
            }
        });
        menuView.add(menuViewDiceThrow);

        menu.add(menuView);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This function is called when the user clicks on the <i>Kampány-kezelő</i> menu item in the <i>Nézetváltás</i> menu.
     * It shows the <code>CampaignPanel</code>, sets the title and hides all the other panels.
     * @param evt 
     */
    private void menuViewCampaignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewCampaignActionPerformed
        this.setTitle("Kampány-kezelő");
        campaignPanel.setVisible(true);
        characterPanel.setVisible(false);
        diceThrowPanel.setVisible(false);
        this.setContentPane(campaignPanel);
    }//GEN-LAST:event_menuViewCampaignActionPerformed

    /**
     * This function is called when the user clicks on the <i>Karakter-kezelő</i> menu item in the <i>Nézetváltás</i> menu.
     * It shows the <code>CharacterPanel</code>, sets the title and hides all the other panels.
     * @param evt 
     */
    private void menuViewCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewCharacterActionPerformed
        this.setTitle("Karakter-kezelő");
        campaignPanel.setVisible(false);
        characterPanel.setVisible(true);
        diceThrowPanel.setVisible(false);
        this.setContentPane(characterPanel);
    }//GEN-LAST:event_menuViewCharacterActionPerformed

    /**
     * This function is called when the user clicks on the <i>Kockadobás</i> menu item in the <i>Nézetváltás</i> menu.
     * It shows the <code>DiceThrowPanel</code>, sets the title and hides all the other panels.
     * @param evt 
     */
    private void menuViewDiceThrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewDiceThrowActionPerformed
        this.setTitle("Kockadobás");
        campaignPanel.setVisible(false);
        characterPanel.setVisible(false);
        diceThrowPanel.setVisible(true);
        this.setContentPane(diceThrowPanel);
    }//GEN-LAST:event_menuViewDiceThrowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DndFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DndFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DndFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DndFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DndFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuView;
    private javax.swing.JMenuItem menuViewCampaign;
    private javax.swing.JMenuItem menuViewCharacter;
    private javax.swing.JMenuItem menuViewDiceThrow;
    // End of variables declaration//GEN-END:variables
}
