package view;

import character.Equipment;
import java.awt.event.KeyEvent;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * Represents a dialog window for the class <code>Equipment</code>.
 */
public class EquipmentEditDialog extends javax.swing.JDialog {
    
    private boolean ok;
    private DefaultComboBoxModel<enums.Type> typeModel = new DefaultComboBoxModel<>(enums.Type.values());
    private Equipment equipment;
    
    /**
     * Creates new form EquipmentEditDialog
     * @param parent parent frame of this dialog
     * @param optEquipment equipment to be modified (empty if new)
     */
    public EquipmentEditDialog(java.awt.Frame parent, Optional<Equipment> optEquipment) {
        super(parent, true);
        initComponents();
        ok = false;
        cbType.setModel(typeModel);
        if (optEquipment.isPresent()) {
            equipment = optEquipment.get();
            typeModel.setSelectedItem(equipment.getType());
            tfName.setText(equipment.getName());
            tfQuantity.setText(String.valueOf(equipment.getQuantity()));
            setTitle("Felszerelés módosítása");
        }
    }
    
    /**
     * Returns <code>true</code> if the user closed the window by clicking on the <i>Ok</i> button.
     * Else it returns <code>false</code>
     * @return if window was closed by clicking the <i>Ok</i> button.
     */
    public boolean isOk() {
        return this.ok;
    }
    
    /**
     * If the window was closed by clicking the <i>Ok</i> button, it returns the equipment based on the input fields of this window.
     * Else it returns an empty <code>Optional</code> 
     * @return an optional equipment
     */
    public Optional<Equipment> getEquipment() {
        Optional<Equipment> optEquipment = Optional.empty();
        if (this.isOk()) {
            Equipment e = new Equipment((enums.Type) typeModel.getSelectedItem(),tfName.getText(), Integer.valueOf(tfQuantity.getText()));
            if (equipment != null) {
                e.setId(equipment.getId());
            }
            optEquipment = Optional.of(e);
        }
        return optEquipment;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lbType = new javax.swing.JLabel();
        cbType = new javax.swing.JComboBox<>();
        lbQuantity = new javax.swing.JLabel();
        tfQuantity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Felszerelés szerkesztés");
        setPreferredSize(new java.awt.Dimension(400, 200));
        setResizable(false);

        lbName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbName.setText("Név:");

        tfName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNameKeyTyped(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Mégsem");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lbType.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbType.setText("Típus:");

        cbType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbQuantity.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbQuantity.setText("Mennyiség:");

        tfQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfQuantityKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbQuantity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(lbName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(lbType)
                                .addGap(10, 10, 10)
                                .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfQuantity)
                    .addComponent(lbQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Felszerelés létrehozása");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This function is called when the user clicks on the <i>Ok</i> button.
     * If any of the input fields are empty, it will show an error.
     * Else it hides the window.
     * @param evt 
     */
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        String error = "";
        if (tfName.getText().isBlank()) {
            error += "Név megadása kötelező!\n";
        }
        if (tfQuantity.getText().isBlank()) {
            error += "Mennyiség megadása kötelező!\n";
        }
        if (!error.isBlank()) {
            JOptionPane.showMessageDialog(this, error, getTitle(), JOptionPane.ERROR_MESSAGE);
            return;
        }
        ok = true;
        setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * This function is called when the user clicks on the <i>Cancel</i> button.
     * It hides the window.
     * @param evt 
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        ok = false;
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * This function is called when the user types in the <code>tfQuantity</code> text field.
     * It only lets the user type in numerical characters.
     * @param evt 
     */
    private void tfQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantityKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0' && c <= '9')) || c == KeyEvent.VK_BACK_SPACE || c== KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_tfQuantityKeyTyped

    /**
     * This function is called when the user types in the <code>tfName</code> text field.
     * It doesn't let the user type in more than 45 characters in the text field.
     * @param evt 
     */
    private void tfNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNameKeyTyped
        if (tfName.getText().length() > 45) {
            evt.consume();
        }
    }//GEN-LAST:event_tfNameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EquipmentEditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EquipmentEditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EquipmentEditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EquipmentEditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EquipmentEditDialog dialog = new EquipmentEditDialog(new javax.swing.JFrame(), Optional.empty());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<enums.Type> cbType;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbQuantity;
    private javax.swing.JLabel lbType;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfQuantity;
    // End of variables declaration//GEN-END:variables
}
